name: newick_utils
description: The Newick Utilities are a suite of Unix shell tools for processing phylogenetic trees
keywords:
    - covid
    - phylogenetic tree
tools:
    - star:
        description: |
            The Newick Utilities are a suite of Unix shell tools for processing phylogenetic trees.
        homepage: https://github.com/tjunier/newick_utils
        manual: https://github.com/tjunier/newick_utils
input:
    - newick:
        type: file
        description: |
            Phylogentic tree in newick format
output:
    - newick:
        type: file
        description: Phylogenetic Tree in Newick format
        pattern: "*.{nwk}"
authors:
    - "@nhhaidee"
