name: iqtree
description: Efficient phylogenetic software by maximum likelihood
keywords:
    - covid
    - Maximum Likelihood
    - Phylogenetic Tree
tools:
    - star:
        description: |
            Multiple alignment program for amino acid or nucleotide sequences
        homepage: https://github.com/Cibiv/IQ-TREE/
        manual: https://github.com/Cibiv/IQ-TREE/
input:
    - fasta:
        type: file
        description: |
            Multiple Sequence Aignment of Consensus Sequenes
output:
    - newick:
        type: file
        description: The Phylogenetic Tree in Newick format
        pattern: "*.{treefile}"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@nhhaidee"
