name: shiptv
description: Generate a standalone html file with an interactive phylogenetic tree using phylocanvas
keywords:
    - covid
    - phylogenetic tree
tools:
    - star:
        description: |
            Generate a standalone html file with an interactive phylogenetic tree using phylocanvas
        homepage: https://github.com/peterk87/shiptv
        manual: https://github.com/peterk87/shiptv
input:
    - newick:
        type: file
        description: |
            Phylogentic tree in newick format
output:
    - newick:
        type: file
        description: Visualization of tree in html file
        pattern: "*.{html}"
authors:
    - "@nhhaidee"